### ISSUE TITLE
Final_data0.cvs

### ISSUE THREAD

**Issue by hrh8867** [tjzxh/HRC-LSTM#3] opened 2020-09-03 06:10 UTC
Hi,
I've read your article and I want to use this dataset for my research. Is it possible for you to send me this dataset?
Here my email:
Hrh8867@gmail.com

Sincerely,

**Comment by tjzxh** [comment] 2021-05-09 02:54
Duplicate of #1

**Closed as completed by tjzxh** 2021-05-09 02:54 UTC
